"""Writes the map reference data into a migration, so `supabase db push` loads it.

Input: site/assets/map/localities.json and land.json (from build_map_data.py).
Output: supabase/migrations/20261006000100_map_data.sql (generated; rerun
after the map data changes)."""
import json, pathlib

root = pathlib.Path(__file__).resolve().parents[3]
locs = json.loads((root / "site/assets/map/localities.json").read_text(encoding="utf-8"))
land = json.loads((root / "site/assets/map/land.json").read_text())

def q(s):
    return "'" + s.replace("'", "''") + "'"

def num(v):
    return "null" if v is None else repr(v)

out = ["-- Generated by tech/tools/supabase/make_seed.py from site/assets/map/*.json. Do not edit by hand.",
       "delete from public.localities where id not in (select locality_id from public.circles);",
       "insert into public.localities (id, name, lat, lon) values"]
out.append(",\n".join(f"({l['id']}, {q(l['name'])}, {num(l.get('lat'))}, {num(l.get('lon'))})" for l in locs))
out[-1] += "\non conflict (id) do update set name = excluded.name, lat = excluded.lat, lon = excluded.lon;"
out.append("delete from public.land_rings;")
for ring in land["rings"]:
    xs = ",".join(repr(p[0]) for p in ring); ys = ",".join(repr(p[1]) for p in ring)
    out.append(f"insert into public.land_rings (xs, ys) values ('{{{xs}}}', '{{{ys}}}');")
dest = root / "supabase/migrations/20261006000100_map_data.sql"
dest.write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"{dest.relative_to(root)}: {len(locs)} localities, {len(land['rings'])} land rings")
